CAMS-146 Add retry to webapp code deploy job
US-Trustee-Program/Bankruptcy-Oversight-Support-Systems pull request #357
Opened 2023-12-08 23:40 UTC by magile32

# Purpose

Intermittent failure sometimes occur during deployment that is not related to recent changes. In most cases, retrying will work the second time but this requires manual intervention.

# Major Changes
- Automate retry of webapp code deployment in an event of a failure

# Testing/Validation

- Verified that retry implementation works, see following [run](https://github.com/US-Trustee-Program/Bankruptcy-Oversight-Support-Systems/actions/runs/7136112398/job/19434284171)

# Notes

New GHA action added. See following actions, https://github.com/nick-fields/retry

2023-12-08 23:44 UTC, magile32 commented on .github/workflows/continuous-deployment.yml
Deploying the webapp code seem to timeout on the Azure side frequently hence the issue. Do we want to apply this to the backend code deployment as well?

2023-12-08 23:54 UTC, governmentSponsored approved these changes

2023-12-11 14:42 UTC, amorrow-flexion approved these changes

2023-12-11 16:06 UTC, amorrow-flexion commented on .github/workflows/continuous-deployment.yml
No harm in also adding it as an extra measure

2023-12-11 16:16 UTC, amorrow-flexion requested changes
We want to remove nick-fields/retry job with 
rerun-failed-jobs:
    runs-on: ubuntu-latest
    needs: [ job1, job2]
    if: failure()
    steps:
      - name: Rerun failed jobs in the current workflow
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh run rerun ${{ github.run_id }} --failed

2023-12-12 16:44 UTC, closed without merging