Cams 49 frontend tests
US-Trustee-Program/Bankruptcy-Oversight-Support-Systems pull request #61
Opened 2023-06-14 15:11 UTC by fmaddenflx

Front-end tests to support Chapter 15 and bring coverage up above 90%

2023-06-15 15:11 UTC, jamesobrooks requested changes
Looks good but I think we should rename `http.humble.ts`.

2023-06-15 15:11 UTC, jamesobrooks commented on user-interface/src/components/utils/http.humble.ts
I think this is more of an adapter than a humble object because we are changing how we call it. Note the following from the OeSA slides on the invasive-species rule:
> Changing semantics is the job of an adapter.

For example we are adding—by default—at least one header and the cache setting.

So I would suggest renaming this to remove `humble` from the name.

2023-06-15 15:11 UTC, jamesobrooks commented on user-interface/src/components/utils/http.humble.ts
Also note that since fetch is part of the language, I don't know that we should have a humble object for it, but it's certainly reasonable to have an adapter.

2023-06-16 15:34 UTC, governmentSponsored commented
@fmaddenflx you may need to pull in main for veracode disabling in case it fails the build on your next commit

2023-06-19 15:06 UTC, jamesobrooks approved these changes
After changing the name we import the http adapter as in a test, this can be merged.

2023-06-19 15:06 UTC, jamesobrooks commented on user-interface/src/models/api.test.ts
> +import * as httpHumble from '../components/utils/http.adapter';
Looks like we need to rename `httpHumble` to `httpAdapter` in this test file.

2023-06-19 16:12 UTC, merged